services:
    #  server:
#    build:
#      context: .
#    ports:
#      - 8081:8081

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker-compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
  db:
    image: postgres:16.4-alpine
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=video-streaming
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    container_name: mykeycloak
    image: quay.io/keycloak/keycloak:25.0.5
    command:
      - start-dev
    ports:
      - "8090:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - keycloak

volumes:
  db-data:
  keycloak-data:
    external: true
networks:
  keycloak:
    external: true
secrets:
  db-password:
    file: db/password.txt

