server:
  port: 8081

spring:
  profiles:
    active: ${PROFILE:local}
  application:
    name: video-streaming-user-service

security:
  jwt:
    secret-key: M0HJO4jIrckccvkOBPv9HPgccXRO5mNx8DAEtPXrMoQ=
    expiration-time: 3600000
