spring:
  security:
    user:
      name: hassan
      password: hassan
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/video-streaming
    username: postgres
    password: ${POSTGRES_PASSWORD:PWH@ss@n}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#logging:
#  level:
#    org.springframework.security: trace